# Generated by Django 6.1.1 on 2026-09-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
