# Generated by Django 6.1.1 on 2026-09-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_foodrawmaterial_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
