# Generated by Django 6.1.1 on 2026-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_foodrawmaterial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
