# Generated by Django 6.1.1 on 2026-09-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_foodrawmaterials_alter_soldoutstatus_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterials',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
