# Generated by Django 6.1.1 on 2026-09-20 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_foods_alter_soldoutstatus_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='foods',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foods',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foods',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
