# Generated by Django 6.1.1 on 2026-09-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_foods_options_foods_data_foods_is_new_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'ordering': ['-price']},
        ),
        migrations.RemoveField(
            model_name='foods',
            name='data',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='name',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='priority',
        ),
    ]
