# Generated by Django 6.1.1 on 2026-09-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_foods_options_remove_foods_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foods',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='foods',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
