# Generated by Django 6.1.1 on 2026-09-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_foods_is_new_foods_name_foods_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
