# Generated by Django 6.1.1 on 2026-09-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_foods_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('details', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=False)),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_food_id', to='menu.mother_food')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
        migrations.AlterField(
            model_name='soldoutstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_out_product', to='menu.foodrawmaterial'),
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
