# Generated by Django 6.1.1 on 2026-09-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_foodrawmaterial_alter_soldoutstatus_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
