# Generated by Django 6.1.1 on 2026-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_foodrawmaterial_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrawmaterial',
            name='extra_data',
        ),
        migrations.AddField(
            model_name='foodrawmaterial',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
