# Generated by Django 5.2.17 on 2026-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_foodrawmaterial_extra_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/food_images/'),
        ),
        migrations.AlterField(
            model_name='mother_food',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soldoutstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
