# Generated by Django 5.2.17 on 2026-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_foodrawmaterial_id_alter_foodrawmaterial_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/food_images/'),
        ),
    ]
