# Generated by Django 6.1.1 on 2026-09-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_foodrawmaterial_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodrawmaterial',
            options={'ordering': ['-price'], 'verbose_name': 'ماده اولیه غذا', 'verbose_name_plural': 'مواد اولیه غذا'},
        ),
        migrations.AlterModelOptions(
            name='mother_food',
            options={'ordering': ['-name'], 'verbose_name': 'غذای مادر', 'verbose_name_plural': 'غذاهای مادر'},
        ),
        migrations.AlterModelOptions(
            name='restaurantbranch',
            options={'verbose_name': 'شعبه رستوران', 'verbose_name_plural': 'شعبه\u200cهای رستوران'},
        ),
        migrations.AlterModelOptions(
            name='soldoutstatus',
            options={'verbose_name': 'وضعیت اتمام موجودی', 'verbose_name_plural': 'وضعیت\u200cهای اتمام موجودی'},
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='زمانی که این رکورد ایجاد شده است', null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='data',
            field=models.JSONField(blank=True, help_text='اطلاعات تکمیلی به\u200cصورت JSON', null=True, verbose_name='داده\u200cهای اضافی'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='details',
            field=models.CharField(blank=True, default='', help_text='توضیحات تکمیلی درباره محصول', max_length=2000, null=True, verbose_name='جزئیات'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='درصد تخفیف محصول (۰ تا ۱۰۰)', max_digits=5, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='image',
            field=models.ImageField(blank=True, help_text='تصویر محصول', null=True, upload_to='static/food_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='is_new',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که محصول جدید است یا نه', verbose_name='محصول جدید'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='mother',
            field=models.ForeignKey(blank=True, help_text='دسته\u200cبندی اصلی که این ماده اولیه به آن تعلق دارد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_food_id', to='menu.mother_food', verbose_name='غذای مادر'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='name',
            field=models.CharField(blank=True, help_text='نام ماده اولیه یا محصول', max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text='قیمت محصول (بدون تخفیف)', null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='priority',
            field=models.IntegerField(default=0, help_text='اولویت نمایش محصول (عدد بزرگ\u200cتر = اولویت بالاتر)', verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='آخرین زمانی که این رکورد ویرایش شده است', null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='mother_food',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mother_food',
            name='name',
            field=models.CharField(help_text='نام دسته\u200cبندی اصلی غذا', max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='حداکثر ظرفیت انبار این شعبه', max_digits=10, null=True, verbose_name='ظرفیت انبار'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='location',
            field=models.CharField(blank=True, help_text='آدرس یا موقعیت شعبه', max_length=200, null=True, verbose_name='موقعیت مکانی'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='name',
            field=models.CharField(help_text='نام شعبه رستوران', max_length=200, verbose_name='نام شعبه'),
        ),
        migrations.AlterField(
            model_name='soldoutstatus',
            name='branch',
            field=models.ForeignKey(help_text='شعبه\u200cای که این وضعیت مربوط به آن است', on_delete=django.db.models.deletion.CASCADE, related_name='sold_out_status', to='menu.restaurantbranch', verbose_name='شعبه'),
        ),
        migrations.AlterField(
            model_name='soldoutstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soldoutstatus',
            name='is_sold_out',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که محصول در این شعبه تمام شده است یا نه', verbose_name='تمام شده'),
        ),
        migrations.AlterField(
            model_name='soldoutstatus',
            name='product',
            field=models.ForeignKey(help_text='محصولی که وضعیت اتمام برای آن ثبت می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='sold_out_product', to='menu.foodrawmaterial', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='soldoutstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='آخرین زمانی که وضعیت به\u200cروزرسانی شده است', verbose_name='تاریخ بروزرسانی'),
        ),
    ]
