# Generated by Django 6.1.1 on 2026-09-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_foodrawmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='foodsoft_id',
            field=models.IntegerField(default=0, help_text='کد ثبت شده در فودسافت', verbose_name='فودسافت کد'),
        ),
    ]
