# Generated by Django 6.1.1 on 2026-09-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_foodrawmaterial_foodsoft_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='مشخص می\u200cکند که محصول نمایش داده میشود یا نه', verbose_name='نمایش محصول'),
        ),
    ]
