# Generated by Django 6.1.1 on 2026-09-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_foodrawmaterial_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='is_active',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که محصول نمایش داده میشود یا نه', verbose_name='نمایش محصول'),
        ),
    ]
